config/routes.rb
Rails.application.routes.draw do
  resources :news_stories
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "news_stories#index"


  get '/exercise' => 'news_stories#werk'
  get '/about' => 'news_stories#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news_story.rb
class NewsStory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/news_stories_controller.rb
class NewsStoriesController < ApplicationController
  before_action :set_news_story, only: [:show, :edit, :update, :destroy]

  # GET /news_stories
  # GET /news_stories.json
  def index
    @news_stories = NewsStory.all
  end

  # GET /news_stories/1
  # GET /news_stories/1.json
  def show
  end

  def werk
    @target_url = params[:url]
    # kinect page get link from index
  end

  # GET /news_stories/new
  def new
    @news_story = NewsStory.new
  end

  # GET /news_stories/1/edit
  def edit
  end

  # POST /news_stories
  # POST /news_stories.json
  def create
    @news_story = NewsStory.new(news_story_params)

    respond_to do |format|
      if @news_story.save
        format.html { redirect_to @news_story, notice: 'News story was successfully created.' }
        format.json { render :show, status: :created, location: @news_story }
      else
        format.html { render :new }
        format.json { render json: @news_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_stories/1
  # PATCH/PUT /news_stories/1.json
  def update
    respond_to do |format|
      if @news_story.update(news_story_params)
        format.html { redirect_to @news_story, notice: 'News story was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_story }
      else
        format.html { render :edit }
        format.json { render json: @news_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_stories/1
  # DELETE /news_stories/1.json
  def destroy
    @news_story.destroy
    respond_to do |format|
      format.html { redirect_to news_stories_url, notice: 'News story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_story
      @news_story = NewsStory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_story_params
      params.require(:news_story).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_stories_helper.rb
module NewsStoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Daily Move</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Custom CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-landing-page/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->


    <link href="https://fonts.googleapis.com/css?family=Old+Standard+TT" rel="stylesheet">
  </head>

  <body>

    <% unless controller_name == 'news_stories' && action_name == 'werk' %>

    <!-- Navigation -->

   <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
       <div class="container">
           <!-- Brand and toggle get grouped for better mobile display -->
           <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
               </button>

               <a class="navbar-brand" href="/">The Daily Move</a>
           </div>
           <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


               <ul class="nav navbar-nav yay">



                   <% if user_signed_in? %>
                   <li>
                       <a href="#"><li class='heythere'>  Hey there, <%= current_user.email %></li></a>
                   </li>
                    <li>
                      <%= link_to 'Edit profile', edit_user_registration_path %>
                    </li>
                    <li>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                    </li>

                    <% else %>
                    <li>
                      <%= link_to "Sign up", new_user_registration_path %> </a>
                   </li>
                   <li>
                      <%= link_to "Login", new_user_session_path %>
                       <% end %></a>
                   </li>
                     <li class='heythere'> <a href="/about">About</a></li>
               </ul>
           </div>

           <!-- /.navbar-collapse -->
       </div>
       <!-- /.container -->
   </nav>
<br>
<br>

   <% end %>

<!--  main bit: -->

  <%= yield %>

<!-- Footer -->

        <% unless controller_name == 'news_stories' && action_name == 'werk' %>

       <footer>
           <div class="row">
               <div class="col-lg-12">
                   <p text-align="right">Copyright &copy; Anusha Rutnam 2017</p>
               </div>
           </div>
           <!-- /.row -->
       </footer>

       <% end %>


</body>

</html>

app/views/news_stories/_form.html.erb
<%= form_with(model: news_story, local: true) do |form| %>
  <% if news_story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news_story.errors.count, "error") %> prohibited this news_story from being saved:</h2>

      <ul>
      <% news_story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :news_story_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news_stories/about.html.erb
 <div class="container">
  <br><br><br>
<p>
Have you ever had the experience of sitting at your computer and realising it has been hours since you stood up and stretched? Well what if you <i>had</i> to exercise in order to access the sweet internet content you crave? Introducing The Daily Move, where you can read the day's latest news stories, but not before you werk for it. Check out the video demo:
</p>

<iframe align="center" width="560" height="315" src="https://www.youtube.com/embed/2FFOrmv0XDE" frameborder="0" allowfullscreen=""></iframe>
<br>
<br>
<a href="https://github.com/a-rutnam/projectthree">And check out the code here.</a>
</div>

app/views/news_stories/edit.html.erb
<h1>Editing News Story</h1>

<%= render 'form', news_story: @news_story %>

<%= link_to 'Show', @news_story %> |
<%= link_to 'Back', news_stories_path %>

app/views/news_stories/index.html.erb
<script>


$(document).ready(function(){


  var baseURL = "https://newsapi.org/v1/articles?source=buzzfeed"
  var newsApiKey = "c21f307cc3974ec1b6900af92dc262ca"


  $.ajax({
      url: baseURL,
      type: "GET",
      data:{
        apiKey: newsApiKey
      }
    })//ajax
    .done(function(response){
      var articlesObj = $(response)


      var articles = response.articles

      for (var i = 0; i < 10; i++) {

  // live site  flydiv:
      // var $flyDiv = '<div class="col-md-4 portfolio-item"><a  href="/exercise?url='+encodeURI(articles[i].url)+'"><img class="img-responsive" src="'+articles[i].urlToImage+'" alt=""></a><h3 class=title>'+articles[i].title+'</h3> <p class=description>'+articles[i].description+'</p></div>'


        //building each newsstory box  on the fly, but with link to demo modal rather than exercise app page
        var $flyDiv = '<div class="col-md-4 portfolio-item" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal'+i+'"><img class="img-responsive" src="'+articles[i].urlToImage+'" alt=""><h3 class=title>'+articles[i].title+'</h3> <p class=description>'+articles[i].description+'</p></div>'

        //three boxes per row
        if (i<3){
          $('.row1').append($flyDiv);
        }else if (i>2 && i<6) {
          $('.row2').append($flyDiv);
        }else if (i>6) {
          $('.row3').append($flyDiv);
        }


        //building modal with corresponding link on the fly
        var $modalDemoLink = '<div id="myModal'+i+'" class="modal fade" role="dialog"> <div class="modal-dialog"> <div class="modal-content"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal">&times;</button> <h4 class="modal-title">Oh no!</h4> </div><div class="modal-body"> <p>Unfortunately, until we put a Kinect in every home, The Daily Move will be in Demo mode, but check out this video of the app in full swing!</p><iframe width="560" height="315" src="https://www.youtube.com/embed/2FFOrmv0XDE" frameborder="0" allowfullscreen></iframe><p><br>p.s. If you actually just want to read the article, do five star-jumps and then <a href="'+articles[i].url+'">Click Here</a></p></div><div class="modal-footer"> <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> </div></div></div></div>'

        $('body').append($modalDemoLink);

      }//fori


    })//done

    .fail(function(xhr, status, err){
      console.log('AJAX ERROR:', xhr, status, err);
    });//fail


});//doc ready

</script>




<!-- Page Content -->
 <div class="container">

       <!-- Page Header -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">The latest news
          <small>...but you'll have to werk for it</small>
        </h1>
      </div>
    </div>

  <div class="row row1"></div>

  <div class="row row2"></div>

  <div class="row row3"></div>


</div>




     <hr>

app/views/news_stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news_story.name %>
</p>

<%= link_to 'Edit', edit_news_story_path(@news_story) %> |
<%= link_to 'Back', news_stories_path %>

app/views/news_stories/werk.html.erb
<script type="text/javascript">
var target_url = '<%= @target_url %>';


var
box,
boxesTouchedCount = 0,
boxTopLeft,
boxBottomRight,
ox = 0,
oy = 0,
oz = 0,
oscy,
oscbut,
pinch,
capture,
pg,
head = false,
h = 0,
i = 0,
j = 0,

controller = null,

joints = {
l_shoulder : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
r_shoulder : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
l_elbow    : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
r_elbow    : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
l_hand     : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
r_hand     : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
l_hip      : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
r_hip      : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
l_knee     : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
r_knee     : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
neck       : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
head       : {x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, ax: 0, ay: 0, az: 0 },
};
var updateJoint = function( jointObj, which, newData ){

  var j = jointObj[ which ];
  if( !j ) return;  // don't bother with joints we haven't initialized in our object
  // velocity
  var newvx = newData.x - j.x;
  var newvy = newData.y - j.y;
  var newvz = newData.z - j.z;
  // acceleration
  j.ax = newvx - j.vx;
  j.ay = newvy - j.vy;
  j.az = newvz - j.vz;
  // velocity
  j.vx = newvx;
  j.vy = newvy;
  j.vz = newvz;
  // position
  j.x = newData.x;
  j.y = newData.y;
  j.z = newData.z;
};//updateJoint

var oscPort = new osc.WebSocketPort({
  url: "ws://localhost:8081" // URL to your Web Socket server.
});

oscPort.open();

oscPort.on("message", function (oscMsg) {
  if(oscMsg.address === '/joint') {
    updateJoint(joints, oscMsg.args[0], {x: oscMsg.args[2], y: oscMsg.args[3], z: oscMsg.args[4]} );
  }
});//oscPort


// function setup(){
//
//   createCanvas(windowWidth, windowHeight);
//
//   colorMode(HSB, 360, 100, 100);
//
//   pg = createGraphics(100, 80);
//
//   textSize(44);
// }//setup


// Draw a line between two joints
var drawSkeletonLine = function( jData, a, b, xRange, yRange ){
  line(
  jData[a].x * xRange,
  jData[a].y * yRange,
  jData[b].x * xRange,
  jData[b].y * yRange
  );
};

function draw(){
  background(0);
  noStroke();

  fill(frameCount%360, 100, 100);

  var depth = map(oz, 0.35, 2.0, 0, 0.5);


  // kinect
  if( joints.l_hand.x  ){
    var handBrowserX = joints.l_hand.x * windowWidth;
    var handBrowserY = joints.l_hand.y * windowHeight;
animateDiv()
  // if (//if hand hits start button, hard coded
  //     handBrowserX >= 500 && handBrowserX <= (650) &&
  //     handBrowserY >= 0 && handBrowserY <= (150)
  //   ){
  //     $("<div class='start'>").hide();
  //     $("<div class='exercise-box'>").show();
  //
  //   }



    //if hand hits deer div element
    for (var i = 0; i < boxes.length; i++) {
      var box = boxes[i];
      // var movingBoxX = parseInt($('.a').position().left)
      // var movingBoxY = parseInt($('.a').position().top)
      var movingBoxX = parseInt($('#box'+i).position().left)
      var movingBoxY = parseInt($('#box'+i).position().top)

      if( box.touched === false &&
        handBrowserX >= movingBoxX && handBrowserX <= (movingBoxX + box.width) &&
        handBrowserY >= movingBoxY  && handBrowserY <= (movingBoxY + box.height)

        // handBrowserX >= box.x && handBrowserX <= (box.x + box.width) &&
        // handBrowserY >= box.y  && handBrowserY <= (box.y + box.height)
      ){
        boxesTouchedCount += 1;
        box.touched = true;
        $('#box' + i).hide();
console.log(boxesTouchedCount);

        if (boxesTouchedCount === boxes.length){
          // $('#moving').show();
          // animateDiv();
          console.log('yay');
          $('#myModal').modal('show');
        }//if all static boxes touched
      }//if any stat box touched
    }//for every box

    // if(
    //   handBrowserX >= movingBoxX && handBrowserX <= (movingBoxX + box.width) &&
    //   handBrowserY >= movingBoxY  && handBrowserY <= (movingBoxY + box.height)
    // ){
      // console.log('yay');
      // $('#myModal').modal('show');
    // }//if movingbox touched

    fill(200, 100, 100);
    // text(oz.toFixed(2),  ox*windowWidth + 20, oy*windowHeight);
    text(`x: ${ joints.l_hand.x.toFixed(2) }`,  20, 40);
    text(`y: ${ joints.l_hand.y.toFixed(2) }`,  20, 80);
    text(`z: ${ joints.l_hand.z.toFixed(2) }`,  20, 120);
    text(`vx: ${ joints.l_hand.vx.toFixed(2) }`, 20, 160);
    text(`vy: ${ joints.l_hand.vy.toFixed(2) }`, 20, 200);
    text(`vz: ${ joints.l_hand.vz.toFixed(2) }`, 20, 240);
    if( controller && controller.xTouch) {
      text(`xT: ${ controller.xTouch.toFixed(2) }`, 20, 300);
    }
    strokeWeight(2);
    stroke(50, 100, 100);
    // drawSkeletonLine(joints, 'neck', 'head', windowWidth, windowHeight);
    var head_width = Math.abs(joints.r_shoulder.x - joints.l_shoulder.x) / 3.0  ;
    var head_left  = joints.head.x - head_width;
    var head_right  = joints.head.x + head_width;
    line(
      head_left*windowWidth, joints.head.y*windowHeight,
      joints.neck.x*windowWidth, joints.neck.y*windowHeight,
    );
    line(
      head_right*windowWidth, joints.head.y*windowHeight,
      joints.neck.x*windowWidth, joints.neck.y*windowHeight,
    );
    line(
      head_right*windowWidth, joints.head.y*windowHeight,
      head_left*windowWidth, joints.head.y*windowHeight,
    );
    drawSkeletonLine(joints, 'r_shoulder', 'r_hip', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'r_shoulder', 'r_elbow', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'r_elbow', 'r_hand', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'l_shoulder', 'r_shoulder', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'l_shoulder', 'l_hip', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'l_shoulder', 'l_elbow', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'l_elbow', 'l_hand', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'l_hip', 'r_hip', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'l_hip', 'l_knee', windowWidth, windowHeight);
    drawSkeletonLine(joints, 'r_hip', 'r_knee', windowWidth, windowHeight);

  }//if joints hands

}//draw function



$(document).ready(function () {
  createCanvas(windowWidth, windowHeight);

  colorMode(HSB, 360, 100, 100);

  pg = createGraphics(100, 80);

  textSize(44);

  // find div position
  // { boxLeft: left, boxTop: top } = $('#deer').position().left;
  boxes = [

  {x: 200, y: 100, width: 100, height: 100, touched: false},
  {x: 500, y: 50, width: 100, height: 100, touched: false},
  {x: 1200, y: 100, width: 100, height: 100, touched: false},
  {x: 100, y: 200, width: 100, height: 100, touched: false},
  {x: 1500, y: 800, width: 100, height: 100, touched: false},
  {x: 700, y: 20, width: 100, height: 100, touched: false},
  {x: 900, y: 50, width: 100, height: 100, touched: false},
  // {x: 1020, y: 110, width: 100, height: 100, touched: false},
  {x: 1600, y: 500, width: 100, height: 100, touched: false},
  // {x: 1300, y: 750, width: 100, height: 100, touched: false},
  // {x: 1400, y: 400, width: 100, height: 100, touched: false},
  // {x: 1440, y: 60, width: 100, height: 100, touched: false},
  // {x: 1600, y: 40, width: 100, height: 100, touched: false},
  ];
  for (var i = 0; i < boxes.length; i++) {
      var box = boxes[i];
      var $boxDiv = $('<div class="exercise-box">').attr('id', 'box'+i).css({
      width:  box.width  + 'px',
      height: box.height + 'px',
      top:  box.y + 'px',
      left: box.x + 'px'
    })
    .appendTo('body');
  }
  // $box = $('#deer');
  // boxTopLeft = $box.position();  //{left: 214, top: 243}
  // boxBottomRight = {
  //   left: boxTopLeft.left + $('#deer').width(),
  //   top:  boxTopLeft.top  + $('#deer').height()
  // };
});//doc ready

function makeNewPosition(){
    // Get viewport dimensions (remove the dimension of the div)
    var h = $(window).height() - 50;
    var w = $(window).width() - 50;
    var nh = Math.floor(Math.random() * h);
    var nw = Math.floor(Math.random() * w);
    return [nh,nw];
}
//moving box
function animateDiv(){
    var newq = makeNewPosition();
    var oldq = $('.a').offset();
    var speed = calcSpeed([oldq.top, oldq.left], newq);
    $('.a').animate({ top: newq[0], left: newq[1] }, speed, function(){
      animateDiv();
      // console.log($('.a.top'));
      // console.log( $('.a').position() );
    });
};

function calcSpeed(prev, next) {
    var x = Math.abs(prev[1] - next[1]);
    var y = Math.abs(prev[0] - next[0]);
    var greatest = x > y ? x : y;
    var speedModifier = 0.1;
    var speed = Math.ceil(greatest/speedModifier);
    return speed;
}


//////////////////////////////
//make boxes:
  function makeNewPosition(){

    // Get viewport dimensions (remove the dimension of the div)
    var h = $(window).height() - 50;
    var w = $(window).width() - 50;

    var nh = Math.floor(Math.random() * h);
    var nw = Math.floor(Math.random() * w);

    return [nh,nw];
  };

  //moving box
  function animateDiv(){

    for (var i = 0; i < boxes.length; i++) {


      var newq = makeNewPosition();
      var oldq = $('#box'+i).offset();
      var speed = calcSpeed([oldq.top, oldq.left], newq);

      $('#box'+i).animate({ top: newq[0], left: newq[1] }, speed, function(){
        animateDiv();
        // console.log($('.a.top'));
        // console.log( $('.a').position() );
      });
    }
  };

  function calcSpeed(prev, next) {

    var x = Math.abs(prev[1] - next[1]);
    var y = Math.abs(prev[0] - next[0]);

    var greatest = x > y ? x : y;

    var speedModifier = 0.1;

    var speed = Math.ceil(greatest/speedModifier);

    return speed;

  }






</script>

<!-- <div class="start" touched="false"><br><br><br><br>Start!</div> -->
<div id="moving" class='a'></div>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>

        </div>
        <div class="modal-body">
          <p> <a class="win" href="<%= @target_url %>">Good job! Click here to be redirect to your article.</a> </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>